version: '3.7'
services:

  # RStudio
  rstudio:
    image: rstudio-3.6.1-deseq
    build:
      context: ../
    environment:
      PASSWORD: "pass"
    ports:
      - "8787:8787"
    volumes:
      - type: bind
        source: ./data
        target: /home/rstudio/data
      - type: bind
        source: ./rscripts
        target: /home/rstudio/rscripts
      - type: volume
        source: r-library
        target: /usr/local/lib/R/library
      - type: volume
        source: r-site-library
        target: /usr/local/lib/R/site-library

volumes:
  r-library:
    driver: local
  r-site-library:
    driver: local
